-- TOKEBakes incremental migration (non-destructive, idempotent)
-- Applies update-signal, sync RPCs, display-order helpers, diagnostics snapshot, and storage policies.

BEGIN;

SET search_path = public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- Ensure base tables/columns exist (without wiping data)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.app_admins (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'owner')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.site_metadata (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '0',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.site_metadata
  ADD COLUMN IF NOT EXISTS version BIGINT,
  ADD COLUMN IF NOT EXISTS last_change_type TEXT;

UPDATE public.site_metadata
SET version = COALESCE(
  version,
  NULLIF(regexp_replace(COALESCE(value, ''), '[^0-9]', '', 'g'), '')::BIGINT,
  0
)
WHERE version IS NULL;

UPDATE public.site_metadata
SET last_change_type = COALESCE(last_change_type, 'all')
WHERE last_change_type IS NULL;

ALTER TABLE public.site_metadata
  ALTER COLUMN version SET DEFAULT 0,
  ALTER COLUMN last_change_type SET DEFAULT 'all';

UPDATE public.site_metadata
SET value = COALESCE(NULLIF(value, ''), COALESCE(version, 0)::TEXT)
WHERE key = 'content_version';

INSERT INTO public.site_metadata (key, value, version, last_change_type, updated_at)
VALUES ('content_version', '0', 0, 'all', now())
ON CONFLICT (key) DO UPDATE
SET version = COALESCE(public.site_metadata.version, 0),
    value = COALESCE(NULLIF(public.site_metadata.value, ''), COALESCE(public.site_metadata.version, 0)::TEXT),
    last_change_type = COALESCE(public.site_metadata.last_change_type, 'all'),
    updated_at = now();

CREATE TABLE IF NOT EXISTS public.site_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL CHECK (event_name ~ '^[a-z0-9_:-]{2,64}$'),
  page_path TEXT,
  session_id TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  source TEXT NOT NULL DEFAULT 'web' CHECK (source IN ('web', 'admin', 'pwa', 'api', 'worker')),
  amount NUMERIC NOT NULL DEFAULT 0 CHECK (amount >= 0),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  phone TEXT,
  message TEXT,
  is_read BOOLEAN NOT NULL DEFAULT false,
  is_archived BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_option_groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES public.menu_items(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'single' CHECK (type IN ('single', 'multiple')),
  required BOOLEAN NOT NULL DEFAULT false,
  max_selections INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_option_values (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id UUID NOT NULL REFERENCES public.product_option_groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price_adjustment NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS public.menu_items
  ADD COLUMN IF NOT EXISTS display_order INTEGER,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}'::TEXT[],
  ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'pastries',
  ADD COLUMN IF NOT EXISTS calories INTEGER;

UPDATE public.menu_items
SET display_order = COALESCE(display_order, 0),
    is_available = COALESCE(is_available, true),
    updated_at = COALESCE(updated_at, now())
WHERE display_order IS NULL OR is_available IS NULL OR updated_at IS NULL;

ALTER TABLE IF EXISTS public.menu_items
  ALTER COLUMN display_order SET DEFAULT 0,
  ALTER COLUMN is_available SET DEFAULT true,
  ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.featured_items
  ADD COLUMN IF NOT EXISTS display_order INTEGER,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS end_date DATE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE public.featured_items
SET display_order = COALESCE(display_order, 0),
    is_active = COALESCE(is_active, true),
    updated_at = COALESCE(updated_at, now())
WHERE display_order IS NULL OR is_active IS NULL OR updated_at IS NULL;

ALTER TABLE IF EXISTS public.featured_items
  ALTER COLUMN display_order SET DEFAULT 0,
  ALTER COLUMN is_active SET DEFAULT true,
  ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.gallery
  ADD COLUMN IF NOT EXISTS display_order INTEGER,
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS price NUMERIC,
  ADD COLUMN IF NOT EXISTS original_price NUMERIC,
  ADD COLUMN IF NOT EXISTS is_special BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS badge_right_text TEXT DEFAULT 'SPECIAL',
  ADD COLUMN IF NOT EXISTS badge_right_icon TEXT DEFAULT chr(128293),
  ADD COLUMN IF NOT EXISTS cta_label TEXT DEFAULT 'Order Now',
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS width INTEGER,
  ADD COLUMN IF NOT EXISTS height INTEGER,
  ADD COLUMN IF NOT EXISTS file_size BIGINT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS public.gallery
  DROP COLUMN IF EXISTS discount_percent;

UPDATE public.gallery
SET display_order = COALESCE(display_order, 0),
    title = COALESCE(NULLIF(trim(title), ''), NULLIF(trim(alt), ''), 'Special Offer'),
    image_url = COALESCE(NULLIF(trim(image_url), ''), NULLIF(trim(image), ''), 'images/logo.webp'),
    image = COALESCE(NULLIF(trim(image), ''), NULLIF(trim(image_url), ''), 'images/logo.webp'),
    price = COALESCE(price, 0),
    is_special = COALESCE(is_special, false),
    badge_right_text = COALESCE(NULLIF(trim(badge_right_text), ''), 'SPECIAL'),
    badge_right_icon = COALESCE(NULLIF(trim(badge_right_icon), ''), chr(128293)),
    cta_label = COALESCE(NULLIF(trim(cta_label), ''), 'Order Now'),
    is_active = COALESCE(is_active, true),
    updated_at = COALESCE(updated_at, now())
WHERE display_order IS NULL
   OR title IS NULL
   OR image_url IS NULL
   OR image IS NULL
   OR price IS NULL
   OR is_special IS NULL
   OR badge_right_text IS NULL
   OR badge_right_icon IS NULL
   OR cta_label IS NULL
   OR is_active IS NULL
   OR updated_at IS NULL;

ALTER TABLE IF EXISTS public.gallery
  ALTER COLUMN display_order SET DEFAULT 0,
  ALTER COLUMN title SET DEFAULT 'Special Offer',
  ALTER COLUMN image_url SET DEFAULT 'images/logo.webp',
  ALTER COLUMN image SET DEFAULT 'images/logo.webp',
  ALTER COLUMN price SET DEFAULT 0,
  ALTER COLUMN is_special SET DEFAULT false,
  ALTER COLUMN badge_right_text SET DEFAULT 'SPECIAL',
  ALTER COLUMN badge_right_icon SET DEFAULT chr(128293),
  ALTER COLUMN cta_label SET DEFAULT 'Order Now',
  ALTER COLUMN is_active SET DEFAULT true,
  ALTER COLUMN updated_at SET DEFAULT now();

DO $$
BEGIN
  IF to_regclass('public.gallery') IS NULL THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.gallery'::regclass
      AND conname = 'gallery_price_nonnegative_chk'
  ) THEN
    ALTER TABLE public.gallery
      ADD CONSTRAINT gallery_price_nonnegative_chk CHECK (price >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.gallery'::regclass
      AND conname = 'gallery_original_price_nonnegative_chk'
  ) THEN
    ALTER TABLE public.gallery
      ADD CONSTRAINT gallery_original_price_nonnegative_chk
      CHECK (original_price IS NULL OR original_price >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.gallery'::regclass
      AND conname = 'gallery_specials_title_len_chk'
  ) THEN
    ALTER TABLE public.gallery
      ADD CONSTRAINT gallery_specials_title_len_chk
      CHECK (title IS NULL OR char_length(trim(title)) BETWEEN 1 AND 120);
  END IF;
END $$;

ALTER TABLE IF EXISTS public.hero_carousel
  ADD COLUMN IF NOT EXISTS display_order INTEGER,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS subtitle TEXT,
  ADD COLUMN IF NOT EXISTS cta_text TEXT,
  ADD COLUMN IF NOT EXISTS cta_link TEXT,
  ADD COLUMN IF NOT EXISTS width INTEGER,
  ADD COLUMN IF NOT EXISTS height INTEGER,
  ADD COLUMN IF NOT EXISTS file_size BIGINT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE public.hero_carousel
SET display_order = COALESCE(display_order, 0),
    is_active = COALESCE(is_active, true),
    updated_at = COALESCE(updated_at, now())
WHERE display_order IS NULL OR is_active IS NULL OR updated_at IS NULL;

ALTER TABLE IF EXISTS public.hero_carousel
  ALTER COLUMN display_order SET DEFAULT 0,
  ALTER COLUMN is_active SET DEFAULT true,
  ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.website_themes
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS logo_file TEXT,
  ADD COLUMN IF NOT EXISTS css_file TEXT,
  ADD COLUMN IF NOT EXISTS theme_name TEXT;

UPDATE public.website_themes
SET created_at = COALESCE(created_at, now()),
    updated_at = COALESCE(updated_at, now()),
    is_active = COALESCE(is_active, false)
WHERE created_at IS NULL OR updated_at IS NULL OR is_active IS NULL;

ALTER TABLE IF EXISTS public.website_themes
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET DEFAULT now(),
  ALTER COLUMN is_active SET DEFAULT false;

ALTER TABLE IF EXISTS public.product_option_groups
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.product_option_values
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE public.product_option_groups
SET updated_at = COALESCE(updated_at, now())
WHERE updated_at IS NULL;

UPDATE public.product_option_values
SET updated_at = COALESCE(updated_at, now())
WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS public.product_option_groups
  ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE IF EXISTS public.product_option_values
  ALTER COLUMN updated_at SET DEFAULT now();

-- =========================================================
-- Indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_site_metadata_key ON public.site_metadata(key);
CREATE INDEX IF NOT EXISTS idx_site_metadata_updated ON public.site_metadata(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_menu_items_display_order ON public.menu_items(display_order ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_featured_items_display_order ON public.featured_items(display_order ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gallery_display_order ON public.gallery(display_order ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gallery_specials_active ON public.gallery(is_active, display_order ASC);
CREATE INDEX IF NOT EXISTS idx_hero_carousel_display_order ON public.hero_carousel(display_order ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_option_groups_product ON public.product_option_groups(product_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_product_option_values_group ON public.product_option_values(group_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_site_events_created_at ON public.site_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_site_events_event_created_at ON public.site_events(event_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_site_events_session_id ON public.site_events(session_id);
CREATE INDEX IF NOT EXISTS idx_site_events_user_id ON public.site_events(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_website_themes_single_active
  ON public.website_themes((is_active))
  WHERE is_active = true;

-- =========================================================
-- Functions
-- =========================================================

CREATE OR REPLACE FUNCTION public.normalize_change_type(p_raw TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN lower(coalesce(trim(p_raw), '')) IN ('menu_options', 'menu-options', 'menuoptions', 'option', 'options') THEN 'menu'
    WHEN lower(coalesce(trim(p_raw), '')) IN ('menu', 'featured', 'gallery', 'carousel', 'theme', 'all') THEN lower(trim(p_raw))
    ELSE 'all'
  END;
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    current_user IN ('postgres', 'supabase_admin')
    OR auth.role() = 'service_role'
    OR EXISTS (
      SELECT 1
      FROM public.app_admins a
      WHERE a.user_id = auth.uid()
    );
$$;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_display_order_default()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  next_order INTEGER;
BEGIN
  IF NEW.display_order IS NULL OR NEW.display_order < 0 THEN
    EXECUTE format('SELECT COALESCE(MAX(display_order), -1) + 1 FROM public.%I', TG_TABLE_NAME)
    INTO next_order;
    NEW.display_order := GREATEST(COALESCE(next_order, 0), 0);
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.normalize_display_order_conflicts()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF pg_trigger_depth() > 1 THEN
    RETURN NULL;
  END IF;

  EXECUTE format(
    'WITH ranked AS (
       SELECT id,
              row_number() OVER (
                ORDER BY COALESCE(display_order, 0) ASC, created_at ASC, id ASC
              ) - 1 AS new_order
       FROM public.%I
     )
     UPDATE public.%I t
     SET display_order = ranked.new_order
     FROM ranked
     WHERE t.id = ranked.id
       AND COALESCE(t.display_order, -1) <> ranked.new_order',
    TG_TABLE_NAME,
    TG_TABLE_NAME
  );

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.bump_update_signal(p_change_type TEXT DEFAULT 'all')
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_change_type TEXT := public.normalize_change_type(p_change_type);
  v_next BIGINT;
BEGIN
  INSERT INTO public.site_metadata (key, value, version, last_change_type, updated_at)
  VALUES ('content_version', '1', 1, v_change_type, now())
  ON CONFLICT (key)
  DO UPDATE SET
    version = GREATEST(public.site_metadata.version, 0) + 1,
    value = (GREATEST(public.site_metadata.version, 0) + 1)::TEXT,
    last_change_type = v_change_type,
    updated_at = now()
  RETURNING version INTO v_next;

  RETURN COALESCE(v_next, 0);
END;
$$;

CREATE OR REPLACE FUNCTION public.bump_content_version()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.bump_update_signal('all');
$$;

CREATE OR REPLACE FUNCTION public.get_update_signal()
RETURNS TABLE (
  content_version BIGINT,
  last_change_type TEXT,
  updated_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    COALESCE(sm.version, 0) AS content_version,
    public.normalize_change_type(sm.last_change_type) AS last_change_type,
    sm.updated_at
  FROM public.site_metadata sm
  WHERE sm.key = 'content_version'
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.get_content_version()
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE((SELECT content_version FROM public.get_update_signal()), 0);
$$;

CREATE OR REPLACE FUNCTION public.site_last_updated()
RETURNS TIMESTAMPTZ
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT GREATEST(
    COALESCE((SELECT max(updated_at) FROM public.menu_items), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT max(updated_at) FROM public.featured_items), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT max(updated_at) FROM public.gallery), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT max(updated_at) FROM public.hero_carousel), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT max(updated_at) FROM public.website_themes), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT max(updated_at) FROM public.product_option_groups), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT max(updated_at) FROM public.product_option_values), 'epoch'::TIMESTAMPTZ),
    COALESCE((SELECT updated_at FROM public.site_metadata WHERE key = 'content_version'), 'epoch'::TIMESTAMPTZ)
  );
$$;

CREATE OR REPLACE FUNCTION public.touch_update_signal()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_change_type TEXT := 'all';
BEGIN
  IF TG_NARGS > 0 AND TG_ARGV[0] IS NOT NULL THEN
    v_change_type := public.normalize_change_type(TG_ARGV[0]);
  END IF;

  PERFORM public.bump_update_signal(v_change_type);
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_active_theme_public()
RETURNS TABLE (
  theme_name TEXT,
  css_file TEXT,
  logo_file TEXT,
  updated_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    wt.theme_name,
    wt.css_file,
    wt.logo_file,
    wt.updated_at
  FROM public.website_themes wt
  WHERE wt.is_active = true
  ORDER BY wt.updated_at DESC NULLS LAST, wt.created_at DESC NULLS LAST
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.can_access_admin_stats()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.is_admin();
$$;

CREATE OR REPLACE FUNCTION public.get_site_state_snapshot()
RETURNS TABLE (
  content_version BIGINT,
  last_change_type TEXT,
  signal_updated_at TIMESTAMPTZ,
  menu_last_updated_at TIMESTAMPTZ,
  featured_last_updated_at TIMESTAMPTZ,
  gallery_last_updated_at TIMESTAMPTZ,
  carousel_last_updated_at TIMESTAMPTZ,
  themes_last_updated_at TIMESTAMPTZ,
  options_last_updated_at TIMESTAMPTZ,
  site_last_updated_at TIMESTAMPTZ,
  active_theme_name TEXT,
  active_theme_css_file TEXT,
  active_theme_logo_file TEXT,
  last_updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.can_access_admin_stats() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  WITH signal AS (
    SELECT
      COALESCE(sm.version, 0) AS content_version,
      public.normalize_change_type(sm.last_change_type) AS last_change_type,
      sm.updated_at AS signal_updated_at
    FROM public.site_metadata sm
    WHERE sm.key = 'content_version'
    LIMIT 1
  ),
  theme AS (
    SELECT
      wt.theme_name,
      wt.css_file,
      wt.logo_file
    FROM public.website_themes wt
    WHERE wt.is_active = true
    ORDER BY wt.updated_at DESC NULLS LAST, wt.created_at DESC NULLS LAST
    LIMIT 1
  )
  SELECT
    COALESCE(s.content_version, 0) AS content_version,
    COALESCE(s.last_change_type, 'all') AS last_change_type,
    s.signal_updated_at,
    (SELECT max(updated_at) FROM public.menu_items) AS menu_last_updated_at,
    (SELECT max(updated_at) FROM public.featured_items) AS featured_last_updated_at,
    (SELECT max(updated_at) FROM public.gallery) AS gallery_last_updated_at,
    (SELECT max(updated_at) FROM public.hero_carousel) AS carousel_last_updated_at,
    (SELECT max(updated_at) FROM public.website_themes) AS themes_last_updated_at,
    GREATEST(
      COALESCE((SELECT max(updated_at) FROM public.product_option_groups), 'epoch'::TIMESTAMPTZ),
      COALESCE((SELECT max(updated_at) FROM public.product_option_values), 'epoch'::TIMESTAMPTZ)
    ) AS options_last_updated_at,
    public.site_last_updated() AS site_last_updated_at,
    t.theme_name AS active_theme_name,
    t.css_file AS active_theme_css_file,
    t.logo_file AS active_theme_logo_file,
    public.site_last_updated() AS last_updated_at
  FROM signal s
  FULL OUTER JOIN theme t ON true
  LIMIT 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.log_site_event(
  p_event_name TEXT,
  p_page_path TEXT DEFAULT NULL,
  p_session_id TEXT DEFAULT NULL,
  p_source TEXT DEFAULT 'web',
  p_amount NUMERIC DEFAULT 0,
  p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id BIGINT;
  v_source TEXT;
BEGIN
  IF p_event_name IS NULL OR btrim(p_event_name) = '' THEN
    RAISE EXCEPTION 'event_name is required' USING ERRCODE = '22023';
  END IF;

  IF lower(btrim(p_event_name)) !~ '^[a-z0-9_:-]{2,64}$' THEN
    RAISE EXCEPTION 'invalid event_name format' USING ERRCODE = '22023';
  END IF;

  v_source := lower(COALESCE(btrim(p_source), 'web'));
  IF v_source NOT IN ('web', 'admin', 'pwa', 'api', 'worker') THEN
    v_source := 'web';
  END IF;

  INSERT INTO public.site_events (
    event_name,
    page_path,
    session_id,
    user_id,
    source,
    amount,
    metadata
  )
  VALUES (
    lower(btrim(p_event_name)),
    NULLIF(left(COALESCE(p_page_path, ''), 512), ''),
    NULLIF(left(COALESCE(p_session_id, ''), 128), ''),
    auth.uid(),
    v_source,
    GREATEST(COALESCE(p_amount, 0), 0),
    COALESCE(p_metadata, '{}'::JSONB)
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_site_stats(p_days INTEGER DEFAULT 30)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_days INTEGER := GREATEST(1, LEAST(COALESCE(p_days, 30), 3650));
  v_from TIMESTAMPTZ := now() - make_interval(days => v_days);
  v_payload JSONB;
BEGIN
  IF NOT public.can_access_admin_stats() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  WITH event_totals AS (
    SELECT
      COUNT(*)::BIGINT AS total_events,
      COUNT(*) FILTER (WHERE event_name = 'page_view')::BIGINT AS page_views,
      COUNT(*) FILTER (WHERE event_name = 'menu_view')::BIGINT AS menu_views,
      COUNT(*) FILTER (WHERE event_name = 'add_to_cart')::BIGINT AS add_to_cart,
      COUNT(*) FILTER (WHERE event_name = 'order_now')::BIGINT AS order_now_clicks,
      COUNT(*) FILTER (WHERE event_name = 'order_submitted')::BIGINT AS orders_submitted,
      COUNT(DISTINCT session_id) FILTER (WHERE session_id IS NOT NULL)::BIGINT AS unique_sessions,
      COALESCE(SUM(amount) FILTER (WHERE event_name = 'order_submitted'), 0)::NUMERIC AS submitted_revenue
    FROM public.site_events
    WHERE created_at >= v_from
  ),
  top_events AS (
    SELECT COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'event_name', t.event_name,
          'count', t.event_count
        )
        ORDER BY t.event_count DESC, t.event_name
      ),
      '[]'::JSONB
    ) AS rows
    FROM (
      SELECT
        se.event_name,
        COUNT(*)::BIGINT AS event_count
      FROM public.site_events se
      WHERE se.created_at >= v_from
      GROUP BY se.event_name
      ORDER BY event_count DESC, se.event_name
      LIMIT 10
    ) t
  ),
  core_totals AS (
    SELECT
      (SELECT COUNT(*)::BIGINT FROM public.menu_items) AS menu_items_total,
      (SELECT COUNT(*)::BIGINT FROM public.menu_items WHERE is_available = true) AS menu_items_active,
      (SELECT COUNT(*)::BIGINT FROM public.featured_items) AS featured_items_total,
      (SELECT COUNT(*)::BIGINT FROM public.featured_items WHERE is_active = true) AS featured_items_active,
      (SELECT COUNT(*)::BIGINT FROM public.gallery) AS gallery_items_total,
      (SELECT COUNT(*)::BIGINT FROM public.hero_carousel) AS carousel_items_total,
      (SELECT COUNT(*)::BIGINT FROM public.product_option_groups) AS option_groups_total,
      (SELECT COUNT(*)::BIGINT FROM public.product_option_values) AS option_values_total,
      (SELECT COUNT(*)::BIGINT FROM public.contact_messages WHERE is_read = false AND is_archived = false) AS unread_messages,
      (SELECT COALESCE(version, 0)::TEXT FROM public.site_metadata WHERE key = 'content_version' LIMIT 1) AS content_version,
      public.site_last_updated() AS site_last_updated
  )
  SELECT jsonb_build_object(
    'window_days', v_days,
    'generated_at', now(),
    'core', jsonb_build_object(
      'menu_items_total', c.menu_items_total,
      'menu_items_active', c.menu_items_active,
      'featured_items_total', c.featured_items_total,
      'featured_items_active', c.featured_items_active,
      'gallery_items_total', c.gallery_items_total,
      'carousel_items_total', c.carousel_items_total,
      'option_groups_total', c.option_groups_total,
      'option_values_total', c.option_values_total,
      'unread_messages', c.unread_messages,
      'content_version', c.content_version,
      'site_last_updated', c.site_last_updated
    ),
    'events', jsonb_build_object(
      'total_events', e.total_events,
      'page_views', e.page_views,
      'menu_views', e.menu_views,
      'add_to_cart', e.add_to_cart,
      'order_now_clicks', e.order_now_clicks,
      'orders_submitted', e.orders_submitted,
      'unique_sessions', e.unique_sessions,
      'submitted_revenue', e.submitted_revenue
    ),
    'top_events', t.rows
  )
  INTO v_payload
  FROM event_totals e
  CROSS JOIN core_totals c
  CROSS JOIN top_events t;

  RETURN v_payload;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_site_stats_daily(p_days INTEGER DEFAULT 30)
RETURNS TABLE (
  day DATE,
  total_events BIGINT,
  page_views BIGINT,
  menu_views BIGINT,
  add_to_cart BIGINT,
  order_now_clicks BIGINT,
  orders_submitted BIGINT,
  submitted_revenue NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_days INTEGER := GREATEST(1, LEAST(COALESCE(p_days, 30), 3650));
  v_from TIMESTAMPTZ := now() - make_interval(days => v_days);
BEGIN
  IF NOT public.can_access_admin_stats() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    date_trunc('day', se.created_at)::DATE AS day,
    COUNT(*)::BIGINT AS total_events,
    COUNT(*) FILTER (WHERE se.event_name = 'page_view')::BIGINT AS page_views,
    COUNT(*) FILTER (WHERE se.event_name = 'menu_view')::BIGINT AS menu_views,
    COUNT(*) FILTER (WHERE se.event_name = 'add_to_cart')::BIGINT AS add_to_cart,
    COUNT(*) FILTER (WHERE se.event_name = 'order_now')::BIGINT AS order_now_clicks,
    COUNT(*) FILTER (WHERE se.event_name = 'order_submitted')::BIGINT AS orders_submitted,
    COALESCE(SUM(se.amount) FILTER (WHERE se.event_name = 'order_submitted'), 0)::NUMERIC AS submitted_revenue
  FROM public.site_events se
  WHERE se.created_at >= v_from
  GROUP BY 1
  ORDER BY 1 DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_site_stats_counts(p_days INTEGER DEFAULT 30)
RETURNS TABLE (
  window_days INTEGER,
  menu_items_total BIGINT,
  menu_items_active BIGINT,
  featured_items_total BIGINT,
  featured_items_active BIGINT,
  gallery_items_total BIGINT,
  carousel_items_total BIGINT,
  option_groups_total BIGINT,
  option_values_total BIGINT,
  unread_messages BIGINT,
  total_events BIGINT,
  page_views BIGINT,
  menu_views BIGINT,
  add_to_cart BIGINT,
  order_now_clicks BIGINT,
  orders_submitted BIGINT,
  unique_sessions BIGINT,
  submitted_revenue NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  j JSONB;
BEGIN
  IF NOT public.can_access_admin_stats() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  j := public.get_site_stats(p_days);

  RETURN QUERY
  SELECT
    COALESCE((j->>'window_days')::INTEGER, p_days),
    COALESCE((j->'core'->>'menu_items_total')::BIGINT, 0),
    COALESCE((j->'core'->>'menu_items_active')::BIGINT, 0),
    COALESCE((j->'core'->>'featured_items_total')::BIGINT, 0),
    COALESCE((j->'core'->>'featured_items_active')::BIGINT, 0),
    COALESCE((j->'core'->>'gallery_items_total')::BIGINT, 0),
    COALESCE((j->'core'->>'carousel_items_total')::BIGINT, 0),
    COALESCE((j->'core'->>'option_groups_total')::BIGINT, 0),
    COALESCE((j->'core'->>'option_values_total')::BIGINT, 0),
    COALESCE((j->'core'->>'unread_messages')::BIGINT, 0),
    COALESCE((j->'events'->>'total_events')::BIGINT, 0),
    COALESCE((j->'events'->>'page_views')::BIGINT, 0),
    COALESCE((j->'events'->>'menu_views')::BIGINT, 0),
    COALESCE((j->'events'->>'add_to_cart')::BIGINT, 0),
    COALESCE((j->'events'->>'order_now_clicks')::BIGINT, 0),
    COALESCE((j->'events'->>'orders_submitted')::BIGINT, 0),
    COALESCE((j->'events'->>'unique_sessions')::BIGINT, 0),
    COALESCE((j->'events'->>'submitted_revenue')::NUMERIC, 0);
END;
$$;

CREATE OR REPLACE FUNCTION public.purge_site_events(p_keep_days INTEGER DEFAULT 180)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_keep_days INTEGER := GREATEST(1, LEAST(COALESCE(p_keep_days, 180), 3650));
  v_deleted INTEGER;
BEGIN
  IF NOT public.can_access_admin_stats() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.site_events
  WHERE created_at < now() - make_interval(days => v_keep_days);

  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$;

-- =========================================================
-- Triggers (drop/recreate safely)
-- =========================================================

DO $$
BEGIN
  IF to_regclass('public.menu_items') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_menu_items ON public.menu_items';
    EXECUTE 'DROP TRIGGER IF EXISTS set_display_order_default_menu_items ON public.menu_items';
    EXECUTE 'DROP TRIGGER IF EXISTS normalize_display_order_menu_items ON public.menu_items';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_menu_items_update_signal ON public.menu_items';

    EXECUTE 'CREATE TRIGGER set_updated_at_menu_items BEFORE UPDATE ON public.menu_items FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER set_display_order_default_menu_items BEFORE INSERT ON public.menu_items FOR EACH ROW EXECUTE FUNCTION public.set_display_order_default()';
    EXECUTE 'CREATE TRIGGER normalize_display_order_menu_items AFTER INSERT OR UPDATE OR DELETE ON public.menu_items FOR EACH STATEMENT EXECUTE FUNCTION public.normalize_display_order_conflicts()';
    EXECUTE 'CREATE TRIGGER trg_menu_items_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.menu_items FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''menu'')';
  END IF;

  IF to_regclass('public.featured_items') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_featured_items ON public.featured_items';
    EXECUTE 'DROP TRIGGER IF EXISTS set_display_order_default_featured_items ON public.featured_items';
    EXECUTE 'DROP TRIGGER IF EXISTS normalize_display_order_featured_items ON public.featured_items';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_featured_items_update_signal ON public.featured_items';

    EXECUTE 'CREATE TRIGGER set_updated_at_featured_items BEFORE UPDATE ON public.featured_items FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER set_display_order_default_featured_items BEFORE INSERT ON public.featured_items FOR EACH ROW EXECUTE FUNCTION public.set_display_order_default()';
    EXECUTE 'CREATE TRIGGER normalize_display_order_featured_items AFTER INSERT OR UPDATE OR DELETE ON public.featured_items FOR EACH STATEMENT EXECUTE FUNCTION public.normalize_display_order_conflicts()';
    EXECUTE 'CREATE TRIGGER trg_featured_items_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.featured_items FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''featured'')';
  END IF;

  IF to_regclass('public.gallery') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_gallery ON public.gallery';
    EXECUTE 'DROP TRIGGER IF EXISTS set_display_order_default_gallery ON public.gallery';
    EXECUTE 'DROP TRIGGER IF EXISTS normalize_display_order_gallery ON public.gallery';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_gallery_update_signal ON public.gallery';

    EXECUTE 'CREATE TRIGGER set_updated_at_gallery BEFORE UPDATE ON public.gallery FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER set_display_order_default_gallery BEFORE INSERT ON public.gallery FOR EACH ROW EXECUTE FUNCTION public.set_display_order_default()';
    EXECUTE 'CREATE TRIGGER normalize_display_order_gallery AFTER INSERT OR UPDATE OR DELETE ON public.gallery FOR EACH STATEMENT EXECUTE FUNCTION public.normalize_display_order_conflicts()';
    EXECUTE 'CREATE TRIGGER trg_gallery_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.gallery FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''gallery'')';
  END IF;

  IF to_regclass('public.hero_carousel') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_hero_carousel ON public.hero_carousel';
    EXECUTE 'DROP TRIGGER IF EXISTS set_display_order_default_hero_carousel ON public.hero_carousel';
    EXECUTE 'DROP TRIGGER IF EXISTS normalize_display_order_hero_carousel ON public.hero_carousel';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_hero_carousel_update_signal ON public.hero_carousel';

    EXECUTE 'CREATE TRIGGER set_updated_at_hero_carousel BEFORE UPDATE ON public.hero_carousel FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER set_display_order_default_hero_carousel BEFORE INSERT ON public.hero_carousel FOR EACH ROW EXECUTE FUNCTION public.set_display_order_default()';
    EXECUTE 'CREATE TRIGGER normalize_display_order_hero_carousel AFTER INSERT OR UPDATE OR DELETE ON public.hero_carousel FOR EACH STATEMENT EXECUTE FUNCTION public.normalize_display_order_conflicts()';
    EXECUTE 'CREATE TRIGGER trg_hero_carousel_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.hero_carousel FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''carousel'')';
  END IF;

  IF to_regclass('public.website_themes') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_website_themes ON public.website_themes';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_website_themes_update_signal ON public.website_themes';

    EXECUTE 'CREATE TRIGGER set_updated_at_website_themes BEFORE UPDATE ON public.website_themes FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER trg_website_themes_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.website_themes FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''theme'')';
  END IF;

  IF to_regclass('public.product_option_groups') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_option_groups ON public.product_option_groups';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_option_groups_update_signal ON public.product_option_groups';
    EXECUTE 'CREATE TRIGGER set_updated_at_option_groups BEFORE UPDATE ON public.product_option_groups FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER trg_option_groups_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.product_option_groups FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''menu'')';
  END IF;

  IF to_regclass('public.product_option_values') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_option_values ON public.product_option_values';
    EXECUTE 'DROP TRIGGER IF EXISTS trg_option_values_update_signal ON public.product_option_values';
    EXECUTE 'CREATE TRIGGER set_updated_at_option_values BEFORE UPDATE ON public.product_option_values FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    EXECUTE 'CREATE TRIGGER trg_option_values_update_signal AFTER INSERT OR UPDATE OR DELETE ON public.product_option_values FOR EACH STATEMENT EXECUTE FUNCTION public.touch_update_signal(''menu'')';
  END IF;

  IF to_regclass('public.site_metadata') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_site_metadata ON public.site_metadata';
    EXECUTE 'CREATE TRIGGER set_updated_at_site_metadata BEFORE UPDATE ON public.site_metadata FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
  END IF;

  IF to_regclass('public.contact_messages') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS set_updated_at_contact_messages ON public.contact_messages';
    EXECUTE 'CREATE TRIGGER set_updated_at_contact_messages BEFORE UPDATE ON public.contact_messages FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
  END IF;
END;
$$;

-- =========================================================
-- RLS + Policies
-- =========================================================

ALTER TABLE IF EXISTS public.app_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.featured_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hero_carousel ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.website_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_option_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.product_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.site_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.site_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contact_messages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF to_regclass('public.app_admins') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS app_admins_read_self_or_admin ON public.app_admins';
    EXECUTE 'DROP POLICY IF EXISTS app_admins_admin_all ON public.app_admins';
    EXECUTE 'CREATE POLICY app_admins_read_self_or_admin ON public.app_admins FOR SELECT TO authenticated USING (public.is_admin() OR user_id = auth.uid())';
    EXECUTE 'CREATE POLICY app_admins_admin_all ON public.app_admins FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.menu_items') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS menu_items_public_read ON public.menu_items';
    EXECUTE 'DROP POLICY IF EXISTS menu_items_admin_all ON public.menu_items';
    EXECUTE 'CREATE POLICY menu_items_public_read ON public.menu_items FOR SELECT TO anon, authenticated USING (is_available = true)';
    EXECUTE 'CREATE POLICY menu_items_admin_all ON public.menu_items FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.featured_items') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS featured_items_public_read ON public.featured_items';
    EXECUTE 'DROP POLICY IF EXISTS featured_items_admin_all ON public.featured_items';
    EXECUTE 'CREATE POLICY featured_items_public_read ON public.featured_items FOR SELECT TO anon, authenticated USING (is_active = true)';
    EXECUTE 'CREATE POLICY featured_items_admin_all ON public.featured_items FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.gallery') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS gallery_public_read ON public.gallery';
    EXECUTE 'DROP POLICY IF EXISTS gallery_admin_all ON public.gallery';
    EXECUTE 'CREATE POLICY gallery_public_read ON public.gallery FOR SELECT TO anon, authenticated USING (true)';
    EXECUTE 'CREATE POLICY gallery_admin_all ON public.gallery FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.hero_carousel') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS hero_carousel_public_read ON public.hero_carousel';
    EXECUTE 'DROP POLICY IF EXISTS hero_carousel_admin_all ON public.hero_carousel';
    EXECUTE 'CREATE POLICY hero_carousel_public_read ON public.hero_carousel FOR SELECT TO anon, authenticated USING (is_active = true)';
    EXECUTE 'CREATE POLICY hero_carousel_admin_all ON public.hero_carousel FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.website_themes') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS website_themes_public_active_read ON public.website_themes';
    EXECUTE 'DROP POLICY IF EXISTS website_themes_admin_all ON public.website_themes';
    EXECUTE 'CREATE POLICY website_themes_public_active_read ON public.website_themes FOR SELECT TO anon, authenticated USING (is_active = true)';
    EXECUTE 'CREATE POLICY website_themes_admin_all ON public.website_themes FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.product_option_groups') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS product_option_groups_public_read ON public.product_option_groups';
    EXECUTE 'DROP POLICY IF EXISTS product_option_groups_admin_all ON public.product_option_groups';
    EXECUTE 'CREATE POLICY product_option_groups_public_read ON public.product_option_groups FOR SELECT TO anon, authenticated USING (EXISTS (SELECT 1 FROM public.menu_items m WHERE m.id = product_option_groups.product_id AND m.is_available = true))';
    EXECUTE 'CREATE POLICY product_option_groups_admin_all ON public.product_option_groups FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.product_option_values') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS product_option_values_public_read ON public.product_option_values';
    EXECUTE 'DROP POLICY IF EXISTS product_option_values_admin_all ON public.product_option_values';
    EXECUTE 'CREATE POLICY product_option_values_public_read ON public.product_option_values FOR SELECT TO anon, authenticated USING (EXISTS (SELECT 1 FROM public.product_option_groups g JOIN public.menu_items m ON m.id = g.product_id WHERE g.id = product_option_values.group_id AND m.is_available = true))';
    EXECUTE 'CREATE POLICY product_option_values_admin_all ON public.product_option_values FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.site_metadata') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS site_metadata_public_read_signal ON public.site_metadata';
    EXECUTE 'DROP POLICY IF EXISTS site_metadata_admin_all ON public.site_metadata';
    EXECUTE 'CREATE POLICY site_metadata_public_read_signal ON public.site_metadata FOR SELECT TO anon, authenticated USING (key = ''content_version'')';
    EXECUTE 'CREATE POLICY site_metadata_admin_all ON public.site_metadata FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;

  IF to_regclass('public.site_events') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS site_events_admin_read ON public.site_events';
    EXECUTE 'DROP POLICY IF EXISTS site_events_admin_delete ON public.site_events';
    EXECUTE 'CREATE POLICY site_events_admin_read ON public.site_events FOR SELECT TO authenticated USING (public.is_admin())';
    EXECUTE 'CREATE POLICY site_events_admin_delete ON public.site_events FOR DELETE TO authenticated USING (public.is_admin())';
  END IF;

  IF to_regclass('public.contact_messages') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS contact_messages_admin_all ON public.contact_messages';
    EXECUTE 'CREATE POLICY contact_messages_admin_all ON public.contact_messages FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin())';
  END IF;
END;
$$;

-- =========================================================
-- Storage buckets/policies
-- =========================================================

DO $$
BEGIN
  IF to_regclass('storage.buckets') IS NOT NULL THEN
    INSERT INTO storage.buckets (id, name, public)
    VALUES
      ('featured-items', 'featured-items', true),
      ('menu-items', 'menu-items', true),
      ('gallery', 'gallery', true),
      ('hero-carousel', 'hero-carousel', true)
    ON CONFLICT (id) DO UPDATE
    SET public = EXCLUDED.public,
        name = EXCLUDED.name;
  END IF;

  IF to_regclass('storage.objects') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS "tb_storage_public_read" ON storage.objects';
    EXECUTE 'DROP POLICY IF EXISTS "tb_storage_admin_write" ON storage.objects';

    EXECUTE $policy$
      CREATE POLICY "tb_storage_public_read"
      ON storage.objects
      FOR SELECT
      TO anon, authenticated
      USING (bucket_id IN ('featured-items', 'menu-items', 'gallery', 'hero-carousel'))
    $policy$;

    EXECUTE $policy$
      CREATE POLICY "tb_storage_admin_write"
      ON storage.objects
      FOR ALL
      TO authenticated
      USING (
        bucket_id IN ('featured-items', 'menu-items', 'gallery', 'hero-carousel')
        AND public.is_admin()
      )
      WITH CHECK (
        bucket_id IN ('featured-items', 'menu-items', 'gallery', 'hero-carousel')
        AND public.is_admin()
      )
    $policy$;
  END IF;
END;
$$;

-- =========================================================
-- Grants
-- =========================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT ON TABLE public.menu_items TO anon, authenticated;
GRANT SELECT ON TABLE public.featured_items TO anon, authenticated;
GRANT SELECT ON TABLE public.gallery TO anon, authenticated;
GRANT SELECT ON TABLE public.hero_carousel TO anon, authenticated;
GRANT SELECT ON TABLE public.website_themes TO anon, authenticated;
GRANT SELECT ON TABLE public.product_option_groups TO anon, authenticated;
GRANT SELECT ON TABLE public.product_option_values TO anon, authenticated;
GRANT SELECT ON TABLE public.site_metadata TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.app_admins TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.menu_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.featured_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.gallery TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.hero_carousel TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.website_themes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.product_option_groups TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.product_option_values TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.site_metadata TO authenticated;
GRANT SELECT, DELETE ON TABLE public.site_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.contact_messages TO authenticated;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_admin_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_update_signal() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_content_version() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.bump_update_signal(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bump_content_version() TO authenticated;
GRANT EXECUTE ON FUNCTION public.site_last_updated() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_active_theme_public() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.log_site_event(TEXT, TEXT, TEXT, TEXT, NUMERIC, JSONB) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_site_stats(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_site_stats_daily(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_site_stats_counts(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.purge_site_events(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_site_state_snapshot() TO authenticated;

COMMIT;

-- Verification
SELECT * FROM public.get_update_signal();
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('site_metadata', 'menu_items', 'featured_items', 'gallery', 'hero_carousel', 'website_themes', 'product_option_groups', 'product_option_values')
ORDER BY table_name;
